import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "./components/AuthProvider";
import "./globals.css";
import UserDropdown from "./components/UserDropdown";






const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "จ่ายด้วย",
  description: "Generated by create next app",
};


export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  /* Suppress ตัวกัน Serverกับ Client รับหน้าที่ทับกัน*/ >
      <body
        
        className={`${geistSans.variable} ${geistMono.variable} antialiased  `}
      >
        
        <AuthProvider>
          {/* ✅ ปุ่ม user ด้านขวาบน */}
          <UserDropdown />

          {/* ✅ เนื้อหาแต่ละหน้า */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}

